services:
  - type: web
    name: ezyago-trading
    env: python
    region: frankfurt
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install --only-binary=cryptography -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ENVIRONMENT
        value: PRODUCTION
      - key: LOG_LEVEL
        value: INFO
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PIP_ONLY_BINARY
        value: ":all:"
    healthCheckPath: /health
    autoDeploy: true